import argparse
import collections
import pathlib
import re
import sys

W, H  = 128, 64

def load_csv(path):
    rows = []
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line:
            continue
        rows.append([1 if c.strip() not in ("", "0") else 0 for c in line.split(",")])
    return rows

def load_png(path):
    try:
        from PIL import Image
    except ImportError:
        sys.exit("PIL module not found. Please install it with 'pip install Pillow'.")
    im = Image.open(path).convert("L")
    return [[1 if im.getpixel((x, y)) > 127 else 0 for x in range(im.width)] 
            for y in range(im.height)]

def load(path):
    rows = load_png(path) if path.suffix.lower() == ".png" else load_csv(path)
    if not rows or len(rows) != H or len(rows[0]) != W:
        sys.exit(f"Invalid image size: expected {W}x{H}, got {len(rows[0]) if rows else 0}x{len(rows) if rows else 0}")
    return rows

# blobs

def blobs(grid):

    seen = [[False] * W for _ in range(H)]
    out = []
    for sy in range(H):
        for sx in range(W):
            if not seen[sy][sx] and grid[sy][sx] == 1:
                # BFS to find the blob
            queue = collections.deque([(sx, sy)])
            seen[sy][sx] = True
            pts = []
            while queue:
                x, y = queue.popleft()
                pts.append((x, y))
                for dx, in (-1, 0, 1):
                    for dy in (-1, 0, 1):
                        nx, ny = x + dx, y + dy
                    if 0 <= nx < W and 0 <= ny < H and not seen[ny][nx] and grid[ny][nx] == 1:
                        seen[ny][nx] = True
                        queue.append((nx, ny))
            x0 = min(p[0] for p in pts); x1 = max(p[0] for p in pts)
            y0 = min(p[1] for p in pts); y1 = max(p[1] for p in pts)
            crop = [[0] * (x1 - x0 + 1) for _ in range(y1 - y0 + 1)]
            for x, y in pts:
                crop[y -y0][x - x0] = 1
            out.append((x0, y0, crop))
    return out


def classify(parts):
    """splitting blobs to left eye and right eye and mouth"""

    groups = {"eyeL": [], "eyeR": [], "mouth": []}
    for x0, y0, crop in parts:
        cx = x0 + len(crop[0]) / 2
        key = "eyeL" if cx < W * 0.42 else "eyeR" if cx > W * 0.58 else "mouth"
        groups[key].append((x0, y0, crop))
    return {k: merge(v) for k, v in groups.items() if v}

def merge(items):

    x0 = min(i[0] for i in items)
    y0 = min(i[1] for i in items)
    x1 = max(i[0] + len(i[2][0]) for i in items)
    y1 = max(i[1] + len(i[2]) for i in items)
    crop = [[0] * (x1 - x0) for _ in range(y1 - y0)]
    for ix, iy, c in items:
        for y, row in enumerate(c):
            for x, v in enumerate(row):
                if v:
                    crop[iy - y0 + y][ix - x0 + x] = 1
    return (x0, y0, crop)

#packing

def pack(crop):
    W = len(crop[0])
    stride = (W + 7) // 8
    data = bytearray()
    for row in crop:
        bs = bytearray(stride)
        for x, v in enumerate(row):
            if v:
                bs[x >> 3] |= 0x80 >> (x & 7)

        data += bs
    return bytes(data), W, len(crop), stride

def ident(name):
    name = re.sub(r"^\d+[_-]", "", name)
    return re.sub(r"[^a-zA-Z0-9_]", "_", name.upper())

#main

def main():
    ap =  argparse.ArgumentParser()
    ap.add_argument("src", help="folder of 128x64 images in .png or .csv format")
    ap.add_argument("-o", "--out", default="face+asset.h")
    ap.add_argument("--preview", action="store_true", help="print ascii of each part")

    args = ap.parse_args()
    files = sorted(p for p in pathlib.Path(args.src).iterdir()
                   if p.suffix.lower() in (".csv", ".png"))
    if not files:
        sys.exit("no .csv/.png found in " + args.src)

    blob_index = {}
    sprites = []
    faces = []

    for f in files:
        parts = classify(blobs(load(f)))
        entry = {}
        for part, (x0, y0, crop) in parts.items():
            data, w, h, _ = pack(crop)
            if data not in blob_index:
                blob_index[data] = len(sprites)
                sprites.append((data, w, h))
            entry[part] = (blob_index[data], x0, y0)
            if args.preview:
                print(f"\n{f.name} :: {part} {w},{h} @ {x0},{y0} sprite #{blob_index[data]}")
                for row in crop:
                    print(" "+"".join("#" if v else "." for v in row))
        for need in ("eyeL", "eyeR", "mouth"):
            if need not in entry:
                sys.exit(f"{f.name}: could not find a '{need}' blob")
        faces.append((ident(f.stem), entry))

    L = []
    A = L.append
    A("// Generated by tools/build_assets.py - do not edit by hand.")
    A(f"// {len(files)} expression(s), {len(sprites)} unique sprite(s).")
    A("#pragma once")
    A("#include <Arduino.h>")
    A("")
    A("struct Sprite { uint8_t w, h; const uint8_t *data; };")
    A("struct Part   { uint8_t spr; uint8_t x, y; };   // x,y = top-left on the 128x64 canvas")
    A("struct Face   { Part eyeL, eyeR, mouth; };")
    A("")

    total = 0
    for i, (data, w, h) in enumerate(sprites):
        stride = (W + 7) // 8
        total += len(data)
        A(f"static const uint8_t SPR_{i}[] PROGMEM = {{ // {w}x{h}, {len(data)} bytes")
        for j in range(h):
            row = data[j * stride:(j + 1) * stride]
            A("  " + ", ".join(f"0x{b:02X}" for b in row) + ",")
        A("};")
    A("")
    A(f"const Sprite SPRITES[] = {{ // {total} bytes of pixels in flash")
    for i, (_, w, h) in enumerate(sprites):
        A(f" {{ {w:3d}, {h:3d}, SPR_{i} }},")
    A("};")
    A("")
    A("enum FaceId : uint8_t {")
    for name, _ in faces:
        A(f" FACE_{name},")
    A(" FACE_COUNT")
    A("};")
    A("")
    A("const Face FACES[FACE_COUNT] = {")
    for name, e in faces:
        cells = ", ".join(f"{{ {e[p][0]}, {e[p][1]:3d}, {e[p][2]:3d} }}" 
                          for p in ("eyeL", "eyeR", "mouth"))
        A(f" {{ {cells} }}, // FACE_{name}")
    A("};")

    out = pathlib.Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(L) + "\n")

    print(f"\n{out}: {len(faces)} face(s), {len(sprites)} sprite(s), {total} bytes of pixel data.")
    print(f"(a fi;;-frame approach would be {len(faces) * 1024} bytes for the same "
          f"{len(faces)} pose(s), before any blinking or gaze")

if __name__ == "__main__":
    main()

