#pragma once
#include <stdint.h>
#include "config.h"

// GENERATED by build_albums.py — do not hand-edit.
// Regenerate with: python3 build_albums.py --manifest albums.json --out <firmware dir>

struct AlbumArt {
  const char    *title;
  const char    *artist;
  const uint16_t palette[PALETTE_SIZE];
  const uint8_t  pixels[ART_PIXELS];
};

extern const AlbumArt ALBUMS[];
extern const uint8_t  ALBUM_COUNT;
